apiVersion: apps/v1
kind: Deployment
metadata:
  name: omv-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: omv-app
  template:
    metadata:
      labels:
        app: omv-app
    spec:
      containers:
        - name: springboot
          image: mayaharitha1/omv-app-img:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: omv-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: omv-app
